[workspace]
members = ["cli", "crates/*"]
resolver = "2"

[workspace.dependencies]
erc20 = { git = "https://github.com/leruaa/erc20-rs" }
alloy = { git = "https://github.com/alloy-rs/alloy" }
num-traits = "0.2"
